config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :mining_types
  get 'welcome/index'
  resources :coins

  root 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coin.rb
# frozen_string_literal: true

class Coin < ApplicationRecord
  # chave estrangeira para mining_type
  belongs_to :mining_type, optional: true
end

app/models/mining_type.rb
class MiningType < ApplicationRecord
  has_many :coins
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    # captura a informação do locales, que será recebida através de um parametro da url. Se essa informação for recebida via url, ela será armazenada dentro de cookies.
    if params[:locale]
      cookies[:locale] = params[:locale]
    end

    # verifica se tem alguma locale guardado dentro de "cookies[:locale], se houver verifica se o locale atual é diferente do guardado no cookie, se for, altera i18n.locale para o local guardado no cookies"

    if cookies[:locale]
      if I18n.locale != cookies[:locale]
        I18n.locale = cookies[:locale]
      end
    end
  end
end

app/controllers/coins_controller.rb
# frozen_string_literal: true

class CoinsController < ApplicationController
  before_action :set_coin, only: %i[show edit update destroy]
  before_action :set_mining_types, only: %i[new edit update create]

  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show; end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit; end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to coin_url(@coin), notice: 'Coin was successfully created.' }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to coin_url(@coin), notice: 'Coin was successfully updated.' }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy

    respond_to do |format|
      format.html { redirect_to coins_url, notice: 'Coin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_mining_types
    @mining_types = MiningType.all.pluck(:description, :id)
  end
  # Use callbacks to share common setup or constraints between actions.
  def set_coin
    @coin = Coin.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def coin_params
    params.require(:coin).permit(:description, :acronym, :url_image, :mining_type_id)
  end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: %i[ show edit update destroy ]

  # GET /mining_types or /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1 or /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types or /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully created." }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1 or /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully updated." }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1 or /mining_types/1.json
  def destroy
    @mining_type.destroy

    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: "Mining type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index
    @nome = params[:nome]
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def br_date(us_date)
    us_date.strftime('%d/%m/%Y')
  end

  def environment_rails
    if Rails.env.development?
      'Desenvolvimento'
    elsif Rails.env.production?
      'Produção'
    else
      'Teste'
    end
  end
end

app/helpers/coins_helper.rb
# frozen_string_literal: true

module CoinsHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_coin.html.erb
<div id="<%= dom_id coin %>">

  <div class="card text-center">
    <div class="card-body">
      <h5 class="card-title"><strong>Description:</strong>
        <%= coin.description %></h5>
      <p class="card-text"> <strong>Acronym:</strong>
        <%= coin.acronym %></p>
      <%= image_tag coin.url_image, size: '25x25' %>

      <p>
        <%= button_to t('links.delete'), @coin, method: :delete, class: 'btn btn-danger' %>
      </p>
    </div>
  </div>
  <br>
</div>

app/views/coins/_form.html.erb
<%= form_with(model: coin) do |form| %>
  <% if coin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
        <% coin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :acronym, style: "display: block" %>
    <%= form.text_field :acronym, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :url_image, style: "display: block" %>
    <%= form.text_field :url_image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :mining_type, style: "display: block" %>
    <%= form.select("mining_type_id", @mining_types, { include_blank: 'Selecione'}, class: 'form-control' ) %>
  </div>

  <div>
    <%= form.submit nil, class: 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<h1><%= t('editing.coin') %></h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to t('links.show'), @coin %> |
  <%= link_to t('links.back'), coins_path %>
</div>

app/views/coins/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= t('thead.coins') %></h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= @coins.human_attribute_name(:description) %></th>
      <th><%= @coins.human_attribute_name(:acronym) %></th>
      <th><%= t('thead.image') %></th>
      <th><%= t('thead.actions') %></th>
    </tr>
  </thead>

  <tbody class="table-group-divider">
    <% @coins.each do |coin| %>
      <tr>
        <td><%= coin.description %></td>
        <td><%= coin.acronym %></td>
        <td> <%= image_tag coin.url_image, width:25, height:25 %> </td>
        <td><%= link_to t('links.show'), coin %></td>
        <td><%= link_to t('links.edit'), edit_coin_path(coin) %></td>
        <td><%= link_to t('links.delete'), coin, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('links.new_coin'), new_coin_path, class: 'btn btn-outline-primary' %>

app/views/coins/new.html.erb
<h1><%= t('links.new_coin') %></h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to t('links.back'), coins_path, class: 'btn btn-outline-primary' %>
</div>

app/views/coins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @coin %>

<div>
  <%= link_to t('links.edit'), edit_coin_path(@coin), class: 'btn btn-outline-primary' %>
  <%= link_to t('links.back'), coins_path, class: 'btn btn-outline-primary' %>
</div>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container-fluid">
      <ul class="nav justify-content-end">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Português (Brasil)", root_path(locale: 'pt-br'), class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "English", root_path(locale: 'en'), class: 'nav-link' %>
        </li>
      </ul>

      <%= yield %>
      <%# # index.html.erb, edit.html.erb %>
    </div>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
          $.notify("Conexão realizada com sucesso!", "success");
        });
    </script>
  </body>
</html>

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type) do |form| %>
  <% if mining_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>

      <ul>
        <% mining_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :acronym, style: "display: block" %>
    <%= form.text_field :acronym, class: "form-control" %>
  </div>
  <br>
  <div class="form-group">
    <%= form.submit nil, class: 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/mining_types/_mining_type.html.erb
<div id="<%= dom_id mining_type %>">

  <div class="card text-center">
    <div class="card-body">
      <h5 class="card-title"><strong>Description:</strong>
        <%= mining_type.description %></h5>
      <p class="card-text"> <strong>Acronym:</strong>
        <%= mining_type.acronym %></p>

      <p>
        <%= button_to t('links.delete'), @mining_type, method: :delete, class: 'btn btn-danger' %>

      </p>
    </div>
  </div>
  <br>

</div>

app/views/mining_types/edit.html.erb
<h1><%= t('editing.mining_type') %></h1>

<%= render "form", mining_type: @mining_type %>

<br>

<div>
  <%= link_to t('showing.mining_type'), @mining_type, class: 'btn btn-outline-primary' %>
  <%= link_to t('links.back'), mining_types_path, class: 'btn btn-outline-primary' %>
</div>

app/views/mining_types/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= t('thead.mining_types') %></h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= @mining_types.human_attribute_name(:description) %></th>
      <th><%= @mining_types.human_attribute_name(:acronym) %></th>
      <th><%= t('thead.actions') %></th>
    </tr>
  </thead>

  <tbody class="table-group-divider">
    <% @mining_types.each do |mining_type| %>
      <tr>
        <td><%= mining_type.description %></td>
        <td><%= mining_type.acronym %></td>
        <td><%= link_to t('links.show'), mining_type %></td>
        <td><%= link_to t('links.edit'), edit_mining_type_path(mining_type) %></td>
        <td><%= link_to t('links.delete'), mining_type, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('links.new_mining_type'), new_mining_type_path, class: 'btn btn-outline-primary' %>

app/views/mining_types/new.html.erb
<h1><%= t('links.new_mining_type') %></h1>

<%= render "form", mining_type: @mining_type %>

<br>

<div>
  <%= link_to t('links.back'), mining_types_path, class: 'btn btn-outline-primary' %>
</div>

app/views/mining_types/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mining_type %>

<div>
  <%= link_to t('links.edit'), edit_mining_type_path(@mining_type), class: 'btn btn-outline-primary' %>
  <%= link_to t('links.back'), mining_types_path, class: 'btn btn-outline-primary' %>

</div>

app/views/welcome/_menu.html.erb
<%= link_to "#{Coin.model_name.human}", 'coins', class: 'btn btn-outline-dark btn-lg', role: 'button' %>

<%= link_to "#{MiningType.model_name.human}", 'mining_types', class:'btn btn-outline-dark btn-lg', role: 'button' %>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= t('welcome') %></h1>

  <p class="lead"> <%= t('messages.welcome') %></p>
  <hr class="my-4">

  <p><%= t('messages.menu') %></p>

  <%= render 'menu' %>

  <h3><%#= t(:hello) %></h3>

  <%# <p>O idioma que está sendo utilizado nessa aplicação é: <strong> = t('current_locale') </strong> </p> %>

  <%# <p><strong>Data:</strong> = br_date(Date.today) </p> %>

</div>